### ISSUE TITLE
Build upon Skin Server

### ISSUE THREAD

**Issue by l89669** [yushijinhun/akir#1]
https://github.com/printempw/blessing-skin-server/issues/65

Maybe use bless skin server as front(make it support the authlib-agent project) is much better than develop a new one?

**Comment by yushijinhun** [comment]
…我的计划是这个项目从零开始写起，不用authlib-agent的那些代码了，到时候会是一个完整的账号系统。至于你说的blessing-skin-server，我完全想不出怎么弄它（因为我不会php）。

**Comment by l89669** [comment]
mc的账号系统也是支持皮肤的，所以我感觉你这个写起来会跟皮肤站很相似。毕竟只要实现注册登陆和创建角色，上传皮肤的功能，这些和皮肤站的功能是百分百重合的。
顺便再脑洞一下，如果能添加角色改名卡功能或许会更棒

**Comment by l89669** [comment]
另外，你为什么不写serverlet而是直接写了个jar？？（大误）

**Comment by yushijinhun** [comment]
用的是spring boot

**Comment by l89669** [comment]
学习了

**Comment by xfl03** [comment]
冒昧插嘴
其实皮肤在Minecraft里的加载或许可以考虑一下CustomSkinLoader而不是authlib-javaagent

**Comment by l89669** [comment]
前端不带皮肤站就没意思了
你要考虑纯净服，而且authlib-agent本来就有部分皮肤站api

**Comment by xfl03** [comment]
@l89669 CustomSkinLoader是一个客户端Mod 和纯净服完全不矛盾 
AA似乎不原生支持高清皮肤呢

**Comment by yushijinhun** [comment]
authlib-agent的定位是一个支持mc全版本的游戏外登录系统。当然因为实现了一整套yggdrasil的api，自然也附带了皮肤站这个功能。而CustomSkinLoader并不是为了登录这个目的，因此两者并不冲突。只不过在使用authlib-agent的情况下，就没有使用CustomSkinLoader的必要了。

**Comment by l89669** [comment]
作者的话正是准确的表达了我说的“authlib-agent本来就有部分皮肤站api”的真正意思=。=
既然
> authlib-agent的定位是一个支持mc全版本的游戏外登录系统

那么实现了这个系统的前端也应该要带有mojang一样的换皮肤的功能
